# ?????????? ??????? dev, ????? Spring ???????? ??????? ?? ?????? ??
spring.profiles.active=dev

# ??????? ?????????
spring.application.name=FitnessApp

# ????????? ???? ?????? (????????? ?????????, ?????? ???????)
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# FatSecret API (????????? ?????? ????????? ?????????)
fatsecret.redirect-uri=http://localhost:8080/callback
fatsecret.auth-url=https://oauth.fatsecret.com/connect/authorize
fatsecret.token-url=https://oauth.fatsecret.com/connect/token
fatsecret.api-url=https://platform.fatsecret.com/rest/server.api
fatsecret.callback-url=http://localhost:8080/fatsecret/callback

# ????????? ?? (Google GenAI)
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.7

# ???????????
spring.cache.cache-names=StudentCache, CourseCache
spring.cache.caffeine.spec=initialCapacity=50,maximumSize=10,expireAfterAccess=300s