-- DDL
CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    email         VARCHAR(50)  NOT NULL,
    password      VARCHAR(255) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp
);

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id   BIGINT      NOT NULL,
    role_name VARCHAR(50) NOT NULL,

    PRIMARY KEY (user_id, role_name),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS fatsecret_day_id_seq  START WITH 1 INCREMENT BY 50;
CREATE TABLE IF NOT EXISTS fatsecret_day
(
    id            BIGINT        NOT NULL DEFAULT nextval('fatsecret_day_id_seq') PRIMARY KEY,
    user_id       BIGINT        NOT NULL,
    date          DATE          NOT NULL,-- LocalDate → DATE, не TIMESTAMP
    date_int      INT,

    calories      DECIMAL(10, 2),
    protein       DECIMAL(10, 2),
    fat           DECIMAL(10, 2),
    carbohydrate  DECIMAL(10, 2),
    version       BIGINT,
    external_hash VARCHAR(64),
    last_sync_at  TIMESTAMPTZ,

    CONSTRAINT uq_fatsecret_day UNIQUE (user_id, date)
);

CREATE SEQUENCE IF NOT EXISTS fatsecret_food_id_seq START WITH 1 INCREMENT BY 50;
CREATE TABLE IF NOT EXISTS fatsecret_food
(
    id                BIGINT        NOT NULL DEFAULT nextval('fatsecret_food_id_seq') PRIMARY KEY,

    external_food_id  BIGINT        NOT NULL,
    external_entry_id BIGINT,
    name              VARCHAR(250)  NOT NULL,
    meal_type         VARCHAR(50)   NOT NULL,

    calories          INT,
    protein           DECIMAL(10, 2),
    fat               DECIMAL(10, 2),
    carbohydrate      DECIMAL(10, 2),

    --@ManyToOne @JoinColumn(name = "day_id")
    day_id            BIGINT,
    CONSTRAINT fk_food_day
        FOREIGN KEY (day_id) REFERENCES fatsecret_day (id)
            ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_external_entry_id ON fatsecret_food (external_entry_id);

CREATE TABLE IF NOT EXISTS fatsecret_connection
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  access_token VARCHAR(250) NOT NULL,
  access_token_secret VARCHAR(250) NOT NULL,

  CONSTRAINT uq_fatsecret_connection_user UNIQUE (user_id),
  CONSTRAINT fk_fatsecret_connection_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS profile
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    goal_weight_kg       DOUBLE PRECISION,
    last_weight_kg       DOUBLE PRECISION,
    height_cm            DOUBLE PRECISION,
    height_measure       VARCHAR(20),
    weight_measure       VARCHAR(20),
    last_weight_date_int INT,

    CONSTRAINT uq_profile_user UNIQUE (user_id),
    CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Sequences
CREATE SEQUENCE IF NOT EXISTS workout_seq  START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS exercise_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS set_seq      START WITH 1 INCREMENT BY 100; -- allocationSize = 100

CREATE TABLE IF NOT EXISTS workout
(
    id       BIGINT NOT NULL DEFAULT nextval('workout_seq') PRIMARY KEY, -- одинарные кавычки
    jefit_id BIGINT,
    date     TIMESTAMP WITH TIME ZONE,
    user_id  BIGINT NOT NULL,

    CONSTRAINT uq_workout_jefit_user UNIQUE (jefit_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_workout_user_date ON workout (user_id, date);

CREATE TABLE IF NOT EXISTS workout_exercises
(
    id            BIGINT        NOT NULL DEFAULT nextval('exercise_seq') PRIMARY KEY,
    jefit_log_id  BIGINT,
    exercise_name VARCHAR(250)  NOT NULL,
    workout_id    BIGINT,

    CONSTRAINT fk_workout_id     FOREIGN KEY (workout_id) REFERENCES workout (id) ON DELETE CASCADE,
    CONSTRAINT uq_exercise_jefit_log UNIQUE (jefit_log_id)
);

CREATE TABLE IF NOT EXISTS workout_sets
(
    id          BIGINT NOT NULL DEFAULT nextval('set_seq') PRIMARY KEY,
    set_index   INT    NOT NULL,
    weight      DOUBLE PRECISION,
    reps        INT    NOT NULL,
    exercise_id BIGINT,

    CONSTRAINT fk_exercise_id FOREIGN KEY (exercise_id) REFERENCES workout_exercises (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS event_publication
(
    id               UUID NOT NULL PRIMARY KEY,
    listener_id      TEXT NOT NULL,
    event_type       TEXT NOT NULL,
    serialized_event TEXT NOT NULL,
    publication_date TIMESTAMP WITH TIME ZONE NOT NULL,
    completion_date  TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS event_publication_by_completion_date
    ON event_publication (completion_date);