CREATE TABLE IF NOT EXISTS ai_insights (
                                           id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           user_id         BIGINT NOT NULL,
                                           insight_type    VARCHAR(20) NOT NULL,
    date            DATE NOT NULL,
    insight_text    TEXT,
    insight_data    JSONB,
    metadata        JSONB,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_ai_insight_user_date_type UNIQUE (user_id, date, insight_type),
    CONSTRAINT fk_ai_insights_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT check_insight_type CHECK (insight_type IN ('daily', 'weekly', 'monthly'))
    );

CREATE INDEX idx_ai_insights_user_date ON ai_insights (user_id, date DESC);
CREATE INDEX idx_ai_insights_date_type ON ai_insights (date, insight_type);
CREATE INDEX idx_ai_insights_user_type ON ai_insights (user_id, insight_type);