CREATE TABLE knowledge_claims (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT NOT NULL,
    subject               VARCHAR(256) NOT NULL,
    subject_normalized    VARCHAR(256) NOT NULL,
    predicate             VARCHAR(128) NOT NULL,
    predicate_normalized  VARCHAR(128) NOT NULL,
    value                 JSONB NOT NULL,
    value_type            VARCHAR(16) NOT NULL,
    unit                  VARCHAR(32),
    origin                VARCHAR(32) NOT NULL,
    verification          VARCHAR(32) NOT NULL,
    temporal_status       VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    confidence_basis      VARCHAR(32) NOT NULL,
    confidence_score      NUMERIC NOT NULL,
    source_type           VARCHAR(64) NOT NULL,
    source_id             VARCHAR(200) NOT NULL,
    source_version        BIGINT NOT NULL,
    observed_at           TIMESTAMPTZ NOT NULL,
    valid_from            TIMESTAMPTZ,
    valid_until           TIMESTAMPTZ,
    content_hash          CHAR(64) NOT NULL,
    schema_version        INTEGER NOT NULL DEFAULT 1,
    supersedes_claim_id   BIGINT,
    aggregate_version     BIGINT NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_knowledge_claims_owner_id UNIQUE (user_id, id),
    CONSTRAINT fk_knowledge_claims_owner FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_claims_supersedes FOREIGN KEY (user_id, supersedes_claim_id)
        REFERENCES knowledge_claims(user_id, id) ON DELETE SET NULL (supersedes_claim_id),
    CONSTRAINT uq_knowledge_claims_source_version_hash
        UNIQUE (user_id, source_type, source_id, source_version, content_hash),
    CONSTRAINT chk_knowledge_claims_subject CHECK (
        length(trim(subject)) BETWEEN 1 AND 256
        AND length(trim(subject_normalized)) BETWEEN 1 AND 256),
    CONSTRAINT chk_knowledge_claims_predicate CHECK (
        length(trim(predicate)) BETWEEN 1 AND 128
        AND length(trim(predicate_normalized)) BETWEEN 1 AND 128),
    CONSTRAINT chk_knowledge_claims_value_object CHECK (
        jsonb_typeof(value) = 'object'
        AND value ? 'value'
        AND value = jsonb_build_object('value', value -> 'value')),
    CONSTRAINT chk_knowledge_claims_value_type CHECK (
        value_type IN ('TEXT', 'BOOLEAN', 'INTEGER', 'DECIMAL', 'DATE', 'INSTANT')),
    CONSTRAINT chk_knowledge_claims_value_shape CHECK (
        (value_type = 'TEXT'
            AND jsonb_typeof(value -> 'value') = 'string'
            AND length(value ->> 'value') BETWEEN 1 AND 4000)
        OR (value_type = 'BOOLEAN' AND jsonb_typeof(value -> 'value') = 'boolean')
        OR (value_type = 'INTEGER'
            AND jsonb_typeof(value -> 'value') = 'number'
            AND value ->> 'value' ~ '^-?(0|[1-9][0-9]*)$')
        OR (value_type = 'DECIMAL' AND jsonb_typeof(value -> 'value') = 'number')
        OR (value_type = 'DATE'
            AND jsonb_typeof(value -> 'value') = 'string'
            AND value ->> 'value' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
        OR (value_type = 'INSTANT'
            AND jsonb_typeof(value -> 'value') = 'string'
            AND value ->> 'value' ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T.+Z$')),
    CONSTRAINT chk_knowledge_claims_unit CHECK (
        unit IS NULL
        OR (value_type IN ('INTEGER', 'DECIMAL') AND length(trim(unit)) BETWEEN 1 AND 32)),
    CONSTRAINT chk_knowledge_claims_origin CHECK (
        origin IN ('USER_DECLARED', 'IMPORTED', 'SYSTEM_DERIVED', 'AI_HYPOTHESIS', 'EXPERIMENT_RESULT')),
    CONSTRAINT chk_knowledge_claims_verification CHECK (
        verification IN ('PROPOSED', 'SUPPORTED', 'REFUTED', 'INCONCLUSIVE', 'DISPUTED')),
    CONSTRAINT chk_knowledge_claims_temporal_status CHECK (
        temporal_status IN ('ACTIVE', 'EXPIRED', 'SUPERSEDED')),
    CONSTRAINT chk_knowledge_claims_confidence_basis CHECK (
        confidence_basis IN ('USER_ASSERTION', 'USER_CONFIRMATION', 'IMPORTED_OBSERVATION',
                             'DETERMINISTIC_RULE', 'AI_MODEL', 'EXPERIMENT_EVIDENCE')),
    CONSTRAINT chk_knowledge_claims_confidence_score CHECK (
        confidence_score BETWEEN 0 AND 1),
    CONSTRAINT chk_knowledge_claims_ai_support CHECK (
        NOT (origin = 'AI_HYPOTHESIS'
             AND verification = 'SUPPORTED'
             AND confidence_basis = 'AI_MODEL')),
    CONSTRAINT chk_knowledge_claims_source_type CHECK (
        source_type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT chk_knowledge_claims_source_id CHECK (
        source_id ~ '^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,199}$'),
    CONSTRAINT chk_knowledge_claims_source_version CHECK (source_version > 0),
    CONSTRAINT chk_knowledge_claims_validity CHECK (
        valid_from IS NULL OR valid_until IS NULL OR valid_from <= valid_until),
    CONSTRAINT chk_knowledge_claims_hash CHECK (content_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_knowledge_claims_schema_version CHECK (schema_version = 1),
    CONSTRAINT chk_knowledge_claims_aggregate_version CHECK (aggregate_version >= 0),
    CONSTRAINT chk_knowledge_claims_timestamps CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_knowledge_claims_one_replacement
    ON knowledge_claims(user_id, supersedes_claim_id)
    WHERE supersedes_claim_id IS NOT NULL;

CREATE INDEX idx_knowledge_claims_active_subject_predicate
    ON knowledge_claims(user_id, subject_normalized, predicate_normalized, valid_from, valid_until)
    WHERE temporal_status = 'ACTIVE';

CREATE INDEX idx_knowledge_claims_freshness
    ON knowledge_claims(user_id, temporal_status, observed_at DESC, id);

CREATE INDEX idx_knowledge_claims_source
    ON knowledge_claims(user_id, source_type, source_id, source_version DESC);

CREATE TABLE knowledge_claim_evidence (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT NOT NULL,
    claim_id          BIGINT NOT NULL,
    evidence_type     VARCHAR(64) NOT NULL,
    evidence_id       VARCHAR(200) NOT NULL,
    evidence_version  BIGINT NOT NULL,
    content_hash      CHAR(64) NOT NULL,
    observed_at       TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_claim_evidence_owner FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_claim_evidence_claim FOREIGN KEY (user_id, claim_id)
        REFERENCES knowledge_claims(user_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_knowledge_claim_evidence_source
        UNIQUE (user_id, claim_id, evidence_type, evidence_id, evidence_version, content_hash),
    CONSTRAINT chk_knowledge_claim_evidence_type CHECK (
        evidence_type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT chk_knowledge_claim_evidence_id CHECK (
        evidence_id ~ '^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,199}$'),
    CONSTRAINT chk_knowledge_claim_evidence_version CHECK (evidence_version > 0),
    CONSTRAINT chk_knowledge_claim_evidence_hash CHECK (content_hash ~ '^[0-9a-f]{64}$')
);

CREATE INDEX idx_knowledge_claim_evidence_claim
    ON knowledge_claim_evidence(user_id, claim_id, observed_at DESC, id);

CREATE TABLE knowledge_claim_command_receipts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT NOT NULL,
    idempotency_key      VARCHAR(128) NOT NULL,
    request_fingerprint  CHAR(64) NOT NULL,
    outcome              VARCHAR(32) NOT NULL,
    result_claim_id      BIGINT,
    result_version       BIGINT NOT NULL,
    source_type          VARCHAR(64) NOT NULL,
    source_id            VARCHAR(200) NOT NULL,
    source_version       BIGINT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_claim_receipts_owner FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_claim_receipts_result FOREIGN KEY (user_id, result_claim_id)
        REFERENCES knowledge_claims(user_id, id) ON DELETE SET NULL (result_claim_id),
    CONSTRAINT uq_knowledge_claim_receipts_owner_key UNIQUE (user_id, idempotency_key),
    CONSTRAINT chk_knowledge_claim_receipts_key CHECK (
        length(trim(idempotency_key)) BETWEEN 1 AND 128),
    CONSTRAINT chk_knowledge_claim_receipts_fingerprint CHECK (
        request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_knowledge_claim_receipts_outcome CHECK (
        outcome IN ('CREATED', 'SUPERSEDED', 'NOOP_STALE', 'NOOP_DELETED', 'DELETED')),
    CONSTRAINT chk_knowledge_claim_receipts_result_version CHECK (result_version >= 0),
    CONSTRAINT chk_knowledge_claim_receipts_source_type CHECK (
        source_type ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT chk_knowledge_claim_receipts_source_id CHECK (
        source_id ~ '^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,199}$'),
    CONSTRAINT chk_knowledge_claim_receipts_source_version CHECK (source_version > 0)
);

CREATE INDEX idx_knowledge_claim_receipts_source_progress
    ON knowledge_claim_command_receipts(user_id, source_type, source_id, source_version DESC, id DESC);
