CREATE TABLE knowledge_claim_usage (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    claim_id    BIGINT NOT NULL,
    purpose     VARCHAR(32) NOT NULL,
    consumer_id VARCHAR(128) NOT NULL,
    used_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_claim_usage_owner FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_claim_usage_claim FOREIGN KEY (user_id, claim_id)
        REFERENCES knowledge_claims(user_id, id) ON DELETE CASCADE,
    CONSTRAINT uq_knowledge_claim_usage_consumer
        UNIQUE (user_id, claim_id, purpose, consumer_id),
    CONSTRAINT chk_knowledge_claim_usage_purpose CHECK (
        purpose IN ('EXPERIMENT_DECISION', 'AI_ANSWER')),
    CONSTRAINT chk_knowledge_claim_usage_consumer CHECK (
        consumer_id ~ '^[A-Za-z0-9][A-Za-z0-9._:@/-]{0,127}$')
);

CREATE INDEX idx_knowledge_claim_usage_owner
    ON knowledge_claim_usage(user_id, used_at DESC, id);

CREATE TABLE knowledge_claim_conflicts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL,
    left_claim_id  BIGINT NOT NULL,
    right_claim_id BIGINT NOT NULL,
    reason         VARCHAR(64) NOT NULL,
    status         VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_claim_conflicts_owner FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_claim_conflicts_left FOREIGN KEY (user_id, left_claim_id)
        REFERENCES knowledge_claims(user_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_knowledge_claim_conflicts_right FOREIGN KEY (user_id, right_claim_id)
        REFERENCES knowledge_claims(user_id, id) ON DELETE CASCADE,
    CONSTRAINT chk_knowledge_claim_conflicts_distinct CHECK (left_claim_id <> right_claim_id),
    CONSTRAINT chk_knowledge_claim_conflicts_reason CHECK (
        reason ~ '^[A-Z][A-Z0-9_]{0,63}$'),
    CONSTRAINT chk_knowledge_claim_conflicts_status CHECK (
        status IN ('OPEN', 'ACKNOWLEDGED', 'DISMISSED'))
);

CREATE INDEX idx_knowledge_claim_conflicts_open
    ON knowledge_claim_conflicts(user_id, status, created_at DESC, id);

CREATE TABLE knowledge_deletion_receipts (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id             BIGINT NOT NULL,
    deleted_claim_id     BIGINT NOT NULL,
    source_fence_hash    CHAR(64) NOT NULL,
    request_fingerprint  CHAR(64) NOT NULL,
    request_key_hash     CHAR(64),
    deleted_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    schema_version       INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_knowledge_deletion_receipts_owner FOREIGN KEY (owner_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_knowledge_deletion_receipts_claim
        UNIQUE (owner_id, deleted_claim_id),
    CONSTRAINT chk_knowledge_deletion_receipts_owner CHECK (owner_id > 0),
    CONSTRAINT chk_knowledge_deletion_receipts_claim CHECK (deleted_claim_id > 0),
    CONSTRAINT chk_knowledge_deletion_receipts_source_hash CHECK (
        source_fence_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_knowledge_deletion_receipts_fingerprint CHECK (
        request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_knowledge_deletion_receipts_key_hash CHECK (
        request_key_hash IS NULL OR request_key_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_knowledge_deletion_receipts_schema CHECK (schema_version = 1)
);

CREATE INDEX idx_knowledge_deletion_receipts_source_fence
    ON knowledge_deletion_receipts(owner_id, source_fence_hash);

CREATE UNIQUE INDEX uq_knowledge_deletion_receipts_request_key
    ON knowledge_deletion_receipts(owner_id, request_key_hash)
    WHERE request_key_hash IS NOT NULL;

ALTER TABLE knowledge_claim_command_receipts
    DROP CONSTRAINT chk_knowledge_claim_receipts_outcome;

ALTER TABLE knowledge_claim_command_receipts
    ADD CONSTRAINT chk_knowledge_claim_receipts_outcome CHECK (
        outcome IN ('CREATED', 'SUPERSEDED', 'NOOP_STALE', 'NOOP_DELETED', 'DELETED',
                    'CONFIRMED', 'DISPUTED'));
