create table user_notes
(
    id          bigint generated by default as identity primary key,
    user_id     bigint not null,
    related_date date    not null,
    content     varchar(500) not null,
    type        varchar(20)  not null,
    created_at  timestamp,
    updated_at  timestamp
);

create index idx_user_notes_user_id on user_notes(user_id);
create index idx_user_notes_related_date on user_notes(related_date);
create index idx_user_notes_user_date on user_notes(user_id, related_date);