-- Create weight_history table for tracking weight over time
CREATE TABLE IF NOT EXISTS weight_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    weight_kg       DECIMAL(5,2) NOT NULL,
    weight_date     DATE NOT NULL,
    weight_source   VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_weight_history_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT chk_weight_source CHECK (weight_source IN ('MANUAL', 'FATSECRET'))
);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_weight_history_user_id ON weight_history (user_id);
CREATE INDEX IF NOT EXISTS idx_weight_history_date ON weight_history (weight_date DESC);
CREATE INDEX IF NOT EXISTS idx_weight_history_user_date ON weight_history (user_id, weight_date DESC);

-- Create unique constraint to prevent duplicate entries per user per date per source
CREATE UNIQUE INDEX IF NOT EXISTS idx_weight_history_user_date_source 
    ON weight_history (user_id, weight_date, weight_source);
